# Generated by Django 3.1.2 on 2020-10-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_auto_20200930_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lo',
            field=models.CharField(default='', max_length=22),
            preserve_default=False,
        ),
    ]
